#include <iostream>
#include <vector>

using namespace std;

int main() {
    int n = 4; // Elements are 0, 1, 2, 3
    
    // 1 << n calculates 2^4 = 16. Loop runs from 0 to 15.
    for (int b = 0; b < (1 << n); b++) {
        vector<int> subset;
        
        // Check each bit from 0 to 3
        for (int i = 0; i < n; i++) {
            // Is the i-th bit turned ON in integer b?
            if (b & (1 << i)) {
                subset.push_back(i);
            }
        }
        
        // Print the subset generated by integer b
        cout << "Integer " << b << " (\t" << b << " in binary) -> { ";
        for (int x : subset) {
            cout << x << " ";
        }
        cout << "}\n";
    }
    
    return 0;
}